name: rdl_torch_tf
channels:
    - pytorch
    - conda-forge
    - defaults
    - bioconda
dependencies:
    - pytorch
    - torchvision
    - torchaudio
    - pip
    - jupyterlab
    - matplotlib
    - pandas
    - pyarrow
    - scikit-learn
    - snakemake
    - xarray
    - zarr
    - tqdm
    - dask
    - pip:
          - tensorflow # or tensorflow-gpu
